spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-recipe
    username: aldora
    password: Tbontb37?
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
